proje15haziran/proje15haziran/Controllers/RoleAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using proje15haziran.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static proje15haziran.Models.UserModel;

namespace proje15haziran.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAdminController : Controller
    {

        private RoleManager<IdentityRole> roleManager;
        private UserManager<ApplicationUser> UserManager;

        public RoleAdminController()
        {
            roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new IdentityDataContext()));
            UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new IdentityDataContext()));

        }
        // GET: RoleAdmin
        public ActionResult Index()
        {
            return View(roleManager.Roles);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string name)
        {
            if (ModelState.IsValid)
            {
                var result = roleManager.Create(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item);
                    }
                }
            }
            return View(name);
        }
        [HttpPost]
        public ActionResult Delete(string id)
        {
            var role = roleManager.FindById(id);
            if (role != null)
            {
                var result = roleManager.Delete(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Role Bulunamadı" });
            }
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            var Role = roleManager.FindById(id);
            var Members = new List<ApplicationUser>();
            var NonMembers = new List<ApplicationUser>();
            foreach (var user in UserManager.Users.ToList())
            {
                var list = UserManager.IsInRole(user.Id, Role.Name) ?
                    Members : NonMembers;
                list.Add(user);
            }
            return View(new RoleEditModel()
            {
                Role= Role,
                Members= Members,
                NonMembers= NonMembers

            });
        }

        [HttpPost]
        public ActionResult Edit(RoleUpdateModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (var userId in model.IdsToAdd ?? new string[] { } )
                {
                    result = UserManager.AddToRole(userId,model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }

                foreach (var userId in model.IdsToDelete ?? new string[] { })
                {
                    result = UserManager.RemoveFromRole(userId, model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");

            }
            return View("Error", new string[] {"Rol Bulunamadı"});
        }
    }

}

proje15haziran/proje15haziran/Views/RoleAdmin/Create.cshtml
@model string
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}

proje15haziran/proje15haziran/Views/RoleAdmin/Edit.cshtml
@model proje15haziran.Models.UserModel.RoleEditModel
@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    <input type="hidden" name="RoleName" value="@Model.Role.Name" />
    <input type="hidden" name="RoleName" value="@Model.Role.Id" />

    <div class="panel panel-primary">
        <div class="panel-heading">
            Add to @Model.Role.Name
        </div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr><td colspan="2">Eklenecek kişi bulunamadı </td></tr>
            }
            else
            {
                <tr>
                    <td>
                        User
                    </td>
                    <td>Role</td>
                </tr>
                foreach (var user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToAdd" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
        
    </div>


    <div class="panel panel-primary">
        <div class="panel-heading">
            Remoce from @Model.Role.Name
        </div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr><td colspan="2">Eklenmiş kişi bulunamadı </td></tr>
            }
            else
            {
                <tr>
                    <td>
                        User
                    </td>
                    <td>Role</td>
                </tr>
                foreach (var user in Model.Members)
                {
                    <tr>
                        <td>@user.UserName</td>
                        <td>
                            <input type="checkbox" name="IdsToDelete" value="@user.Id" />
                        </td>
                    </tr>
                }
            }
        </table>
        
    </div>

    <button type="submit"class="btn btn-primary">Kaydet</button>
}

proje15haziran/proje15haziran/Views/RoleAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Roller
    </div>
</div>
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="3">Rol Yok</td>
        </tr>
    }
    else
    {
        foreach (var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td>
                    @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                    {
                        @Html.ActionLink("Güncelle", "Edit", new { id = role.Id }, new { @class = "btn btn-primary btn-sm" })
                        <button tpye="submit" class="btn btn-danger btn-sm">Delete</button>
                    }
                </td>

            </tr>
        }
    }


</table>